apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keda-logs-file
  namespace: openshift-keda
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem