apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2025-08-28T04:24:56Z"
  name: system:openshift:scc:anyuid
  namespace: traefik
  resourceVersion: "166101"
  uid: cd20f5d8-a853-4e46-9151-d1ea701502e8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: traefik