apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
      - traefik
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
    scheme: http
    interval: 30s
    scrapeTimeout: 10s